# Generated by Django 2.2.6 on 2019-10-28 21:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.CharField(choices=[('doing', 'Doing'), ('done', 'Done')], default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
    ]
